"""change the name of columns in history table

Revision ID: 6766ead065a0
Revises: 
Create Date: 2024-03-21 00:29:47.593342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6766ead065a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filtering_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enterWord_1', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('enterWord_2', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('enterWord_3', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('politics', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('criminal', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sexual', sa.Boolean(), nullable=True))
        batch_op.drop_column('checkbox_option2')
        batch_op.drop_column('choice2')
        batch_op.drop_column('choice3')
        batch_op.drop_column('checkbox_option3')
        batch_op.drop_column('checkbox_option1')
        batch_op.drop_column('choice1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filtering_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choice1', mysql.VARCHAR(length=25), nullable=True))
        batch_op.add_column(sa.Column('checkbox_option1', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('checkbox_option3', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('choice3', mysql.VARCHAR(length=25), nullable=True))
        batch_op.add_column(sa.Column('choice2', mysql.VARCHAR(length=25), nullable=True))
        batch_op.add_column(sa.Column('checkbox_option2', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('sexual')
        batch_op.drop_column('criminal')
        batch_op.drop_column('politics')
        batch_op.drop_column('enterWord_3')
        batch_op.drop_column('enterWord_2')
        batch_op.drop_column('enterWord_1')

    # ### end Alembic commands ###
