"""divide history table for 3 tables

Revision ID: 9378efeeeeae
Revises: 6766ead065a0
Create Date: 2024-04-01 15:10:36.198492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9378efeeeeae'
down_revision = '6766ead065a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('politics', sa.Boolean(), nullable=True),
    sa.Column('criminal', sa.Boolean(), nullable=True),
    sa.Column('sexual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['filtering_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('enterWord_1', sa.String(length=25), nullable=True),
    sa.Column('enterWord_2', sa.String(length=25), nullable=True),
    sa.Column('enterWord_3', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['filtering_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filtering_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('data_type', sa.String(length=25), nullable=False))
        batch_op.drop_column('criminal')
        batch_op.drop_column('politics')
        batch_op.drop_column('enterWord_2')
        batch_op.drop_column('enterWord_3')
        batch_op.drop_column('sexual')
        batch_op.drop_column('enterWord_1')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filtering_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('enterWord_1', mysql.VARCHAR(length=25), nullable=True))
        batch_op.add_column(sa.Column('sexual', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('enterWord_3', mysql.VARCHAR(length=25), nullable=True))
        batch_op.add_column(sa.Column('enterWord_2', mysql.VARCHAR(length=25), nullable=True))
        batch_op.add_column(sa.Column('politics', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('criminal', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('data_type')
        batch_op.drop_column('date_created')

    op.drop_table('words_history')
    op.drop_table('option_history')
    # ### end Alembic commands ###
